### ISSUE TITLE
có 🐛 spam là crash và block chèn nhau juy 😂

### ISSUE THREAD

**Issue by SupBi** [MinhMiner672/Tetris#2]
ảnh spam: ![image](https://user-images.githubusercontent.com/93335301/151127845-88a99a31-f0e7-4c3d-b722-e6ade951abbf.png)
block chèn nhau m thấy r juy

**Comment by SupBi** [comment]
juy

**Comment by SupBi** [comment]
fix đi dm 😂

**Comment by MinhMiner672** [comment]
đang bận đm, giỏi thì contribute hộ cái 😂😂😂🤏

**Comment by SupBi** [comment]
> đang bận đm, giỏi thì contribute hộ cái 😂😂😂🤏

juy juy 😂

**Comment by MinhMiner672** [comment]
fixed 👍
